Set-Service -Name BTAGService -StartupType Disabled -ErrorAction SilentlyContinue
Set-Service -Name bthserv -StartupType Disabled -ErrorAction SilentlyContinue
Set-Service -Name icssvc -StartupType Disabled -ErrorAction SilentlyContinue
Set-Service -Name LanmanServer -StartupType Disabled -ErrorAction SilentlyContinue
Set-Service -Name lfsvc -StartupType Disabled -ErrorAction SilentlyContinue
Set-Service -Name lltdsvc -StartupType Disabled -ErrorAction SilentlyContinue
Set-Service -Name MapsBroker -StartupType Disabled -ErrorAction SilentlyContinue
Set-Service -Name MSiSCSI -StartupType Disabled -ErrorAction SilentlyContinue
Set-Service -Name p2pimsvc -StartupType Disabled -ErrorAction SilentlyContinue
Set-Service -Name p2psvc -StartupType Disabled -ErrorAction SilentlyContinue
Set-Service -Name PNRPAutoReg -StartupType Disabled -ErrorAction SilentlyContinue
Set-Service -Name PNRPsvc -StartupType Disabled -ErrorAction SilentlyContinue
Set-Service -Name PushToInstall -StartupType Disabled -ErrorAction SilentlyContinue
Set-Service -Name RasAuto -StartupType Disabled -ErrorAction SilentlyContinue
Set-Service -Name RpcLocator -StartupType Disabled -ErrorAction SilentlyContinue
Set-Service -Name SessionEnv -StartupType Disabled -ErrorAction SilentlyContinue
Set-Service -Name SharedAccess -StartupType Disabled -ErrorAction SilentlyContinue
Set-Service -Name Spooler -StartupType Disabled -ErrorAction SilentlyContinue
Set-Service -Name SSDPSRV -StartupType Disabled -ErrorAction SilentlyContinue
Set-Service -Name TermService -StartupType Disabled -ErrorAction SilentlyContinue
Set-Service -Name UmRdpService -StartupType Disabled -ErrorAction SilentlyContinue
Set-Service -Name upnphost -StartupType Disabled -ErrorAction SilentlyContinue
Set-Service -Name Wecsvc -StartupType Disabled -ErrorAction SilentlyContinue
Set-Service -Name wercplsupport -StartupType Disabled -ErrorAction SilentlyContinue
Set-Service -Name WerSvc -StartupType Disabled -ErrorAction SilentlyContinue
Set-Service -Name WinRM -StartupType Disabled -ErrorAction SilentlyContinue
Set-Service -Name WMPNetworkSvc -StartupType Disabled -ErrorAction SilentlyContinue
Set-Service -Name WpnService -StartupType Disabled -ErrorAction SilentlyContinue
Set-Service -Name XblAuthManager -StartupType Disabled -ErrorAction SilentlyContinue
Set-Service -Name XblGameSave -StartupType Disabled -ErrorAction SilentlyContinue
Set-Service -Name XboxGipSvc -StartupType Disabled -ErrorAction SilentlyContinue
Set-Service -Name XboxNetApiSvc -StartupType Disabled -ErrorAction SilentlyContinue